### ISSUE TITLE
Error de lógica

### ISSUE THREAD

**Issue by alanbalfonso** [AngelLizardo-Waggamer/RetosPOO#4]
En el reto textualmente decía y cito: "Los valores que contendrá el vector son agregados de manera automática y aleatoria tomando el rango del 1 al 100. "
Durante la ejecución del programa me percaté de que se hizo caso omiso a esta proposición, por lo tanto existe un error, gracias por su comprensión.

**Comment by AngelLizardo-Waggamer** [comment]
The issue was corrected following the challenge rubric, thank you!
